ZHANG_WONYOUNG_ORIGINAL_COLOR_THEMES = [
    "navy cropped football-inspired jersey with clean contrast trim, paired with a white high-waist pleated tennis mini skirt, white over-the-knee socks, and football sneakers, sporty idol styling",
    "white sleeveless sailor top with a large navy sailor collar and oversized navy ribbon, paired with a navy layered ruffle mini skirt, polished stage styling",
    "white sleeveless fitted pointed-collar blouse with a black decorative necktie, paired with a brown plaid high-waist pleated mini skirt, British preppy styling",
    "black fitted straight-neck camisole mini dress with restrained gold ring strap details, long satin opera gloves, and a black choker, elegant cocktail styling",
    "navy-and-white striped knitted bandeau top with light-blue high-waist straight-leg jeans and an oversized denim jacket as a relaxed outer layer, urban airport styling",
    "black sleeveless fine-rib knit fit-and-flare mini dress with opaque openwork stripe texture and a softly flared skirt, minimal Parisian styling",
    "white fitted camisole with a navy high-waist tiered ruffle mini skirt and white sneakers, cute idol styling",
    "white fitted half-turtleneck short-sleeve knit top with charcoal washed bootcut jeans, minimal casual styling",
    "white lace-trim ribbed camisole under an oversized black blazer, paired with black relaxed trousers or a matching skirt, minimal backstage styling",
    "sage-green cropped graphic-free T-shirt layered over a green striped button-up shirt, paired with light-wash straight jeans, Korean preppy styling",
    "white fitted performance polo top with a white high-waist pleated tennis skirt, white crew socks, and tennis shoes, clean tennis-club styling",
    "black sleeveless fine-rib knit mini dress with opaque openwork stripe texture, a cinched waist, and softly flared skirt, understated French styling",
    "white fitted lace-trim camisole under an oversized black bomber jacket, paired with black relaxed cargo pants and chunky sneakers, backstage casual styling",
    "white sleeveless sailor dress with a navy sailor collar, oversized ribbon, structured waist, and double-layer ruffle hem, school-idol styling",
    "navy cropped supporter-style jersey with clean white trim, paired with a white high-waist pleated cheer skirt, white over-the-knee socks, and trainers, energetic sporty styling",
    "dusty-pink cropped fine-knit cardigan over a white mock-neck chiffon blouse, paired with a black high-waist knife-pleated mini skirt and black loafers, soft Korean preppy styling",
    "oversized white cropped athletic T-shirt with opaque ventilation-knit shoulder panels, paired with navy lightweight running shorts, white crew socks, and black retro running shoes, clean sporty styling",
    "oversized navy cropped opaque performance-knit sports jersey with white rib trim, paired with a pale-blue high-waist tennis skort, white knee-high socks, and silver retro trainers, athletic idol styling",
    "black fitted bandeau knit top with a black-and-ivory striped crochet cardigan and matching high-waist mini skirt, French resort styling",
    "white ribbed lace-trim camisole under an oversized black zip hoodie, paired with black relaxed wide-leg pants, minimal backstage styling",
    "oversized cream padded jacket with matching cream straight-leg trousers and tan suede ankle boots, soft winter minimal styling",
    "butter-yellow cropped tweed jacket with matching high-waist tweed shorts and a white floral-embellished fitted T-shirt, soft luxury preppy styling",
    "white ribbed baby T-shirt layered under a heather-gray ribbed henley tank, paired with mid-rise blue straight jeans, everyday Korean casual styling",
    "oversized light-gray graphic-free T-shirt with an ivory textured floral-embroidered midi skirt, relaxed soft daily styling",
    "white oversized cotton T-shirt with a white eyelet-lace tiered mini skirt, bright-red crew socks, and black Mary Jane flats, French picnic styling",
    "black fitted short-sleeve knit top with white contrast trim and a small neckline bow, paired with an ivory gathered mini skirt and black ballet flats, French sweet casual styling",
    "black fitted square-neck camisole midi dress with a clean column silhouette, modern Korean minimalist styling",
    "pastel-blush one-shoulder mini dress with a softly gathered bodice, wrapped waist draping, and structured tulip skirt, polished event styling",
    "white cropped baseball-inspired jersey with red-and-navy sleeve trim, paired with light-blue high-waist straight-leg jeans and white retro sneakers, fresh sporty styling",
    "white oversized zip-up track jacket with black sleeve stripes and matching white straight track pants, clean Y2K sports styling",
    "heather-gray fitted ribbed camisole layered over a white short-sleeve baby T-shirt, paired with a black high-waist pleated tennis skirt and loafers, Korean campus styling",
    "black fitted spaghetti-strap camisole with vintage-blue high-rise straight-leg jeans and an oversized black zip hoodie as a relaxed outer layer, off-duty model styling",
    "cream lightweight crochet-knit short-sleeve top with a small white neckline bow, paired with a dusty-pink gathered high-waist skirt and cream Mary Jane shoes, soft vintage styling",
    "ivory sleeveless cotton-linen sundress with a square neckline, gathered bodice, high waist, and flowing A-line skirt, fresh countryside styling",
    "oversized ivory cropped athletic sweatshirt with a charcoal-gray pleated tennis skort, white knee-high socks, and silver retro running shoes, soft sporty airport styling",
]


ZHANG_WONYOUNG_COLOR_FREE_THEMES = [
    "cropped football-inspired jersey with clean contrast trim, paired with a high-waist pleated tennis mini skirt, over-the-knee socks, and football sneakers, sporty idol styling",
    "sleeveless sailor top with a large sailor collar and oversized ribbon, paired with a layered ruffle mini skirt, polished stage styling",
    "sleeveless fitted pointed-collar blouse with a decorative necktie, paired with a plaid high-waist pleated mini skirt, British preppy styling",
    "fitted straight-neck camisole mini dress with restrained metallic ring strap details, long satin opera gloves, and a slim choker, elegant cocktail styling",
    "striped knitted bandeau top with high-waist straight-leg jeans and an oversized denim jacket as a relaxed outer layer, urban airport styling",
    "sleeveless fine-rib knit fit-and-flare mini dress with opaque openwork stripe texture and a softly flared skirt, minimal Parisian styling",
    "fitted camisole with a high-waist tiered ruffle mini skirt and clean sneakers, cute idol styling",
    "fitted half-turtleneck short-sleeve knit top with washed bootcut jeans, minimal casual styling",
    "lace-trim ribbed camisole under an oversized blazer, paired with relaxed trousers or a matching skirt, minimal backstage styling",
    "cropped graphic-free T-shirt layered over a striped button-up shirt, paired with light-wash straight jeans, Korean preppy styling",
    "fitted performance polo top with a high-waist pleated tennis skirt, crew socks, and tennis shoes, clean tennis-club styling",
    "sleeveless fine-rib knit mini dress with opaque openwork stripe texture, a cinched waist, and softly flared skirt, understated French styling",
    "fitted lace-trim camisole under an oversized bomber jacket, paired with relaxed cargo pants and chunky sneakers, backstage casual styling",
    "sleeveless sailor dress with a contrast sailor collar, oversized ribbon, structured waist, and double-layer ruffle hem, school-idol styling",
    "cropped supporter-style jersey with clean contrast trim, paired with a high-waist pleated cheer skirt, over-the-knee socks, and trainers, energetic sporty styling",
    "cropped fine-knit cardigan over a mock-neck chiffon blouse, paired with a high-waist knife-pleated mini skirt and loafers, soft Korean preppy styling",
    "oversized cropped athletic T-shirt with opaque ventilation-knit shoulder panels, paired with lightweight running shorts, crew socks, and retro running shoes, clean sporty styling",
    "oversized cropped opaque performance-knit sports jersey with rib trim, paired with a high-waist tennis skort, knee-high socks, and retro trainers, athletic idol styling",
    "fitted bandeau knit top with a striped crochet cardigan and matching high-waist mini skirt, French resort styling",
    "ribbed lace-trim camisole under an oversized zip hoodie, paired with relaxed wide-leg pants, minimal backstage styling",
    "oversized padded jacket with matching straight-leg trousers and suede ankle boots, soft winter minimal styling",
    "cropped tweed jacket with matching high-waist tweed shorts and a floral-embellished fitted T-shirt, soft luxury preppy styling",
    "ribbed baby T-shirt layered under a ribbed henley tank, paired with straight jeans, everyday Korean casual styling",
    "oversized graphic-free T-shirt with a textured floral-embroidered midi skirt, relaxed soft daily styling",
    "oversized cotton T-shirt with an eyelet-lace tiered mini skirt, contrast crew socks, and Mary Jane flats, French picnic styling",
    "fitted short-sleeve knit top with contrast trim and a small neckline bow, paired with a gathered mini skirt and ballet flats, French sweet casual styling",
    "fitted square-neck camisole midi dress with a clean column silhouette, modern Korean minimalist styling",
    "one-shoulder mini dress with a softly gathered bodice, wrapped waist draping, and structured tulip skirt, polished event styling",
    "cropped baseball-inspired jersey with contrast sleeve trim, paired with high-waist straight-leg jeans and retro sneakers, fresh sporty styling",
    "oversized zip-up track jacket with contrast sleeve stripes and matching straight track pants, clean Y2K sports styling",
    "fitted ribbed camisole layered over a short-sleeve baby T-shirt, paired with a high-waist pleated tennis skirt and loafers, Korean campus styling",
    "fitted spaghetti-strap camisole with high-rise straight-leg jeans and an oversized zip hoodie as a relaxed outer layer, off-duty model styling",
    "lightweight crochet-knit short-sleeve top with a small neckline bow, paired with a gathered high-waist skirt and Mary Jane shoes, soft vintage styling",
    "sleeveless cotton-linen sundress with a square neckline, gathered bodice, high waist, and flowing A-line skirt, fresh countryside styling",
    "oversized cropped athletic sweatshirt with a pleated tennis skort, knee-high socks, and retro running shoes, soft sporty airport styling",
]
