"""User-selectable fixed prompts for D-mode target-image batches."""

PROMPT_SETS: tuple[str, ...] = (
    """masterpiece, best quality, ultra detailed, anime cinematic portrait composition, use the reference image only as character appearance reference,

extreme close-up composition,
three-quarter side profile framing,
character positioned slightly off-center,
camera placed slightly below eye level,
soft upward viewing angle,

focus on elegant neck line and shoulder silhouette,
large empty negative space around the face,
clean bright background with soft blur,
strong facial focal point,
intimate portrait atmosphere,

eyes looking toward viewer from the corner of the frame,
subtle smile,
hair partially covering one eye,
foreground hair strands creating depth,

soft natural lighting,
high contrast between shadow and skin highlights,
gentle rim light around hair,
cinematic depth of field,
background heavily blurred,

delicate skin reflections,
high detail eyelashes and eyes,
smooth composition flow from eyes → lips → neck → shoulder,

minimalist framing,
modern anime illustration style,
vertical mobile wallpaper composition,
high-end character illustration aesthetic""",
    """masterpiece,
best quality,
premium Japanese anime portrait illustration,

use the character reference only as appearance and identity reference,
faithfully preserve the character’s recognizable facial features,
hairstyle design,
hair color,
eye color,
eye shape,
accessories,
and overall youthful anime proportions,

do not copy the pose or composition from the character reference,
apply the following portrait composition independently,

extreme close-up character portrait,
intimate tightly framed composition,
head, face, neck, shoulder, and partial upper torso visible,

three-quarter side profile,
body turned partially away from the viewer,
head gently turned back toward the viewer over the shoulder,
subtle over-the-shoulder portrait feeling,

face viewed from a strong three-quarter angle,
one side of the face more visible than the other,
nose and lips forming a delicate side-profile contour,
chin slightly lowered,
head slightly tilted,

camera positioned approximately at eye level or slightly above,
close portrait viewing distance,
natural compressed perspective,
no wide-angle distortion,
no exaggerated foreshortening,

character positioned slightly above and off-center,
face located near the upper-middle focal region,
visible shoulder occupying part of the lower-middle composition,
shoulder line naturally leading toward the neck and face,

eyes looking sideways toward the viewer,
soft indirect eye contact,
slightly lowered eyelids,
calm intimate gaze,
subtle restrained smile,
relaxed delicate lips,
quiet and slightly mysterious expression,

hair partially covering one eye,
soft layered bangs crossing the forehead and cheek,
several larger hair locks framing the face,

long or loose hair flowing dynamically around the character,
hair spreading through the surrounding composition,
broad sweeping hair shapes filling much of the frame,
curving hair masses creating circular visual movement around the face,

foreground hair sweeping across the lower frame and side edges,
some strands passing close to the camera,
soft foreground occlusion,
foreground hair partially out of focus,
natural layered depth,

use large coherent hair groups rather than countless individual strands,
detailed hair only near the face,
outer hair shapes simplified into elegant flowing silhouettes,
controlled natural hair movement,
no chaotic strand explosion,

strong visual flow:
eye → cheek → lips → jawline → neck → exposed shoulder,
with surrounding hair curves continuously guiding attention back toward the face,

elegant neck line,
delicate collarbone indication,
soft shoulder silhouette,
upper body used as a secondary compositional shape,
face remains the unquestionable focal point,

soft matte anime skin,
minimal skin texture,
delicate blush around cheeks,
clean elegant facial rendering,
refined anime eyes,
restrained eyelashes,
small delicate mouth,
subtle nose rendering,

soft luminous anime lighting,
bright diffused key light falling across the face,
gentle illuminated cheek and eye area,
soft shadow on the opposite side of the face,

delicate rim light along hair edges,
translucent light passing through thin hair strands,
soft luminous highlights inside the hair,
gentle atmospheric glow around the silhouette,

controlled soft bloom around the brightest highlights,
dreamlike luminous atmosphere,
bright but never overexposed,

foreground slightly darker than the illuminated face,
subtle foreground framing,
soft contrast between luminous focal areas and darker surrounding shapes,

background heavily simplified,
soft abstract gradient or atmospheric background,
very subtle distant particles or tiny light specks,
background detail kept extremely low,

the surrounding hair acts as the primary environmental framing element,
no unnecessary scenery competing with the character,

dense but organized portrait composition,
frame mostly occupied by character, hair, and foreground shapes,
very little unused negative space,

strong depth hierarchy:
soft foreground hair,
sharp facial focal plane,
layered middle-ground hair,
simple atmospheric background,

limited cohesive color palette,
one dominant atmospheric color family across the entire image,
character’s original colors preserved while harmonized with the surrounding light,
soft complementary accent colors allowed,
controlled saturation,
no random multicolor lighting,

highest detail concentrated on:
visible eye,
eyelashes,
lips,
facial contour,
nearby bangs,
neck and shoulder transition,

medium detail on surrounding hair,
low detail toward the outer frame and background,

premium Japanese 2D anime key visual,
polished light-novel-cover quality,
refined linework,
layered cel shading with restrained soft transitions,
clean color separation,
elegant shape design,
lightweight but highly polished rendering,

avoid:
front-facing portrait,
symmetrical composition,
straight passport-photo framing,
low-angle heroic perspective,
wide-angle distortion,
large empty background areas,
static hair,
flat hair silhouette,
random hair strands,
excessive individual hair detail,
chaotic wind effects,
overrendering,
AI detail noise,
excessive skin texture,
photorealistic skin,
semi-realistic painting,
3D render,
plastic anime look,
heavy cinematic shadows,
harsh contrast,
strong volumetric lighting,
excessive bloom,
overexposure,
RGB lighting,
random fantasy effects,
overcomplicated background,
decorative clutter,
oversharpening,
overly glossy eyes,
generic AI anime style""",
    """masterpiece, best quality, ultra detailed, premium Japanese anime illustration, cinematic character portrait, use the reference image only as character appearance reference, faithfully preserve the character’s recognizable hairstyle, hair color, eye color, facial features, accessories, outfit design, and overall visual identity,

knee-up portrait composition,
character framed from the head to approximately just above the knees,
head, torso, hips, and upper legs clearly visible,
character occupying approximately 75–90% of the frame height,
balanced medium-full portrait distance,
three-quarter side profile,
slightly turned upper body and hips,
asymmetrical off-center framing,
head positioned slightly toward one side of the canvas,
body extending naturally through the lower frame,
intentional cropping slightly above the knees,
strong character presence while preserving an elegant cinematic portrait feeling,

camera positioned slightly below eye level,
subtle low-angle perspective,
gentle upward viewing direction,
natural portrait lens perspective,
moderate camera distance,
camera far enough to comfortably include the body from head to above the knees,
no wide-angle facial or body distortion,
no exaggerated perspective,
keep head-to-body proportions elegant, balanced, and natural,

emphasize the facial contour, jawline, elegant neck line, collarbone, shoulders, torso, natural waist, hips, and upper-leg silhouette,
shoulders slightly angled rather than perfectly frontal,
subtle torso rotation creating depth,
hips naturally following or gently counterbalancing the shoulder angle,
natural transition from ribcage → waist → hips → thighs,
clear but understated waistline,
natural pelvic alignment,
balanced body proportions,
smooth visual flow from eyes → lips → jawline → neck → shoulders → waist → hips → upper legs,

natural standing pose,
body weight distributed primarily onto one leg,
subtle relaxed contrapposto,
one hip slightly shifted,
one leg positioned subtly forward or backward to create depth,
thighs following the natural direction of the hips,
knees aligned naturally with the legs,
avoid rigid symmetrical stance,
avoid exaggerated hip tilt,
avoid unnatural twisting,
graceful and relaxed body language,

both arms anatomically complete and naturally connected to the shoulders,
relaxed natural arm positioning,
arms positioned clearly enough to preserve the body silhouette,
one arm may rest naturally beside the body or bend gently near the waist,
the other arm may enter slightly closer to the foreground to strengthen depth,
hands naturally visible when appropriate,
natural shoulders, elbows, wrists, fingers, and hand proportions,
avoid awkward arm crossing,
avoid arms disappearing behind the torso without clear anatomical continuity,
avoid duplicated, disconnected, or malformed limbs,

eyes turned subtly toward the viewer from the side,
sideways eye contact,
calm and intimate gaze,
slightly lowered eyelids,
subtle restrained smile,
natural relaxed lips,
quiet, elegant, emotionally intimate expression,

hair partially covering one eye,
several loose foreground hair strands crossing near the camera,
layered hair locks creating subtle foreground depth,
soft overlapping hair around the cheek, jaw, neck, and shoulders,
longer hair naturally flowing across or behind the torso when appropriate,
natural strand separation,
delicate wind-swept feeling without excessive movement,
hair movement complementing rather than obscuring the body silhouette,

clearly readable outfit from shoulders through the waist, hips, and upper legs,
preserve the character’s original clothing design, colors, accessories, and recognizable costume details,
natural fabric tension around shoulders, chest, waist, hips, elbows, and upper legs,
refined fabric folds following the torso, hip, arm, and leg movement,
accurate garment construction,
clear layering of clothing pieces,
clean readable silhouette,
natural interaction between clothing and body,
avoid excessive clothing deformation,
avoid clothing fused with limbs,
avoid exaggerated body contours beneath clothing,

intentional negative space beside and above the character,
sufficient breathing room around the head and body silhouette,
minimalist bright background,
clean high-key backdrop,
soft luminous gradient,
very subtle environmental shapes,
background strongly defocused and visually unobtrusive,
no distracting objects,
background supporting the full character silhouette without competing for attention,

soft directional natural light,
delicate light falling across the face and body from one side,
controlled contrast between soft shadows and luminous highlights,
subtle shadow beneath the jaw and around the neck,
gentle modeling across the torso, waist, hips, and thighs,
gentle rim light tracing the outer hair, shoulders, arms, waist, hips, and upper-leg silhouette,
soft reflected light along the cheek, lips, neck, collarbone, arms, clothing, and legs,
cinematic highlight control,
no harsh overexposure,

highly detailed anime eyes,
precise iris reflections,
fine eyelashes,
delicate eyelid shading,
subtle catchlights,
refined nose and lip shading,
clean facial planes,
smooth anime skin rendering with restrained luminous reflections,
detailed but clean clothing rendering,
precise accessories,
refined hands and fingers,
clean anatomical transitions throughout the body,
no photorealistic skin texture,

moderately shallow depth of field,
sharpest focus on the nearest visible eye and facial features,
face, torso, waist, hips, and upper legs remaining clearly readable,
gradual and controlled softness toward areas farther from the focal plane,
foreground hair or hand subtly blurred only when very close to the camera,
background heavily blurred,
cinematic optical depth,
avoid excessive depth-of-field blur across the character,
maintain sufficient clarity from head to knees,

premium hand-drawn Japanese 2D anime key visual,
clean refined lineart,
elegant line-weight variation,
layered cel shading with restrained soft transitions,
luminous illustrated lighting,
high-end light-novel cover quality,
modern Japanese character illustration aesthetic,

minimalist editorial knee-up portrait framing,
intimate cinematic atmosphere,
elegant and sophisticated composition,
strong facial focal point supported by graceful body posing,
natural body language,
balanced character silhouette,
balanced negative space,
vertical mobile wallpaper composition,
3:4 aspect ratio,

avoid: extreme close-up framing, waist-up framing, full-body framing, feet visible, cropping at the hips, cropping through the middle of the thighs, face filling most of the frame, oversized head, undersized body, chibi proportions, centered passport-style composition, rigid front-facing pose, rigid symmetrical stance, excessive headroom, overly distant camera, extreme low angle, wide-angle distortion, exaggerated perspective, oversized nose, protruding chin, unnaturally long neck, excessively narrow shoulders, broken shoulder anatomy, twisted torso, distorted ribcage, distorted waist, broken pelvis anatomy, exaggerated hip width, unnatural hip rotation, excessively long or short torso, excessively long or short legs, malformed thighs, disconnected legs, extra legs, missing limbs, disconnected arms, extra arms, duplicated hands, malformed hands, fused fingers, awkward elbows, stiff arm positioning, unnatural body proportions, exaggerated chest, exaggerated waist, exaggerated hips, stiff expression, exaggerated smile, crossed eyes, flat lighting, excessive depth-of-field blur, cluttered background, photorealism, semi-realistic painting, 3D render, plastic skin""",
    """masterpiece, best quality, ultra detailed, premium Japanese anime illustration, cinematic character portrait, use the reference image only as character appearance reference, faithfully preserve the character’s recognizable hairstyle, hair color, eye color, facial features, accessories, outfit design, and overall visual identity,

waist-up portrait composition,
character framed from the head to approximately the natural waist,
upper body occupying approximately 65–80% of the frame height,
three-quarter side profile,
slightly turned upper body,
asymmetrical off-center framing,
head positioned slightly toward one side of the canvas,
waist and torso naturally extending toward the lower frame,
intentional partial cropping near the waist and outer arm edges,
strong character presence while preserving an intimate portrait feeling,

camera positioned slightly below eye level,
subtle low-angle perspective,
gentle upward viewing direction,
natural portrait lens perspective,
moderate camera distance,
no wide-angle facial or body distortion,
keep facial and upper-body proportions elegant, compact, and natural,

emphasize the facial contour, jawline, elegant neck line, collarbone, shoulders, upper torso, and natural waist silhouette,
shoulders slightly angled rather than perfectly frontal,
subtle torso rotation creating depth,
one shoulder positioned slightly closer to the camera,
natural transition from shoulders through torso toward the waist,
clear but understated waistline,
smooth visual flow from eyes → lips → jawline → neck → shoulder → torso → waist,

both arms anatomically complete and naturally connected to the shoulders,
relaxed natural arm positioning,
one arm may enter slightly closer to the foreground to strengthen depth,
hands either naturally visible within the composition or intentionally cropped near the lower frame,
natural elbows, wrists, and fingers,
avoid awkward arm crossing,
avoid hidden or disconnected limbs,
avoid duplicated arms or hands,

eyes turned subtly toward the viewer from the side,
sideways eye contact,
calm and intimate gaze,
slightly lowered eyelids,
subtle restrained smile,
natural relaxed lips,
quiet, elegant, emotionally intimate expression,

hair partially covering one eye,
several loose foreground hair strands crossing close to the camera,
layered hair locks creating foreground depth,
soft overlapping hair around the cheek, jaw, neck, and shoulder,
longer hair naturally flowing across or behind the upper body when appropriate,
natural strand separation,
delicate wind-swept feeling without excessive movement,

clearly readable outfit from shoulders to waist,
preserve the character’s original clothing design and recognizable costume details,
natural fabric tension around shoulders, chest, elbows, and waist,
refined fabric folds following the torso and arm movement,
accurate garment construction,
clean silhouette,
avoid excessive clothing deformation,
avoid exaggerated body contours,

intentional negative space beside and above the character,
minimalist bright background,
clean high-key backdrop,
soft luminous gradient,
very subtle environmental shapes,
background strongly defocused and visually unobtrusive,
no distracting objects,

soft directional natural light,
delicate light falling across the face and upper body from one side,
controlled contrast between soft shadows and luminous highlights,
subtle shadow beneath the jaw and around the neck,
gentle rim light tracing the outer hair, shoulder, and upper-body silhouette,
soft reflected light along the cheek, lips, neck, collarbone, arms, and clothing,
cinematic highlight control,
no harsh overexposure,

highly detailed anime eyes,
precise iris reflections,
fine eyelashes,
delicate eyelid shading,
subtle catchlights,
refined nose and lip shading,
clean facial planes,
smooth anime skin rendering with restrained luminous reflections,
detailed but clean clothing rendering,
no photorealistic skin texture,

shallow depth of field,
sharpest focus on the nearest visible eye and facial features,
face and upper torso remaining clearly readable,
slightly softer hair and body areas farther from the focal plane,
foreground hair or foreground arm subtly blurred when close to the camera,
background heavily blurred,
cinematic optical depth,
maintain sufficient clarity across the character’s upper body,

premium hand-drawn Japanese 2D anime key visual,
clean refined lineart,
elegant line-weight variation,
layered cel shading with restrained soft transitions,
luminous illustrated lighting,
high-end light-novel cover quality,
modern Japanese character illustration aesthetic,

minimalist editorial waist-up portrait framing,
intimate cinematic atmosphere,
elegant and sophisticated composition,
strong facial focal point supported by graceful upper-body posing,
natural body language,
balanced negative space,
vertical mobile wallpaper composition,
3:4 aspect ratio,

avoid: extreme close-up framing, face filling most of the frame, full-body framing, knees or feet visible, centered passport-style composition, rigid front-facing pose, excessive headroom, overly distant camera, wide-angle distortion, oversized head, undersized torso, oversized nose, protruding chin, unnaturally long neck, excessively narrow shoulders, broken shoulder anatomy, twisted torso, distorted waist, disconnected arms, missing arms, extra arms, duplicated hands, malformed hands, fused fingers, awkward elbows, stiff arm positioning, unnatural body proportions, exaggerated chest or waist, stiff expression, exaggerated smile, crossed eyes, flat lighting, cluttered background, photorealism, semi-realistic painting, 3D render, plastic skin""",
)
